<?php

namespace AppleMusic;

class LanguageCodes
{
    const LANGUAGE_CODE_AFRIKAANS = 'af';
    const LANGUAGE_CODE_ARABIC = 'ar';
    const LANGUAGE_CODE_BENGALI = 'bn';
    const LANGUAGE_CODE_BULGARIAN = 'bg';
    const LANGUAGE_CODE_CANTONESE = 'yue-Hant';
    const LANGUAGE_CODE_CATALAN = 'ca';
    const LANGUAGE_CODE_CHINESE_SIMPLIFIED = 'cmn-Hans';
    const LANGUAGE_CODE_CHINESE_TRADITIONAL = 'cmn-Hant';
    const LANGUAGE_CODE_CROATIAN = 'hr';
    const LANGUAGE_CODE_CZECH = 'cs';
    const LANGUAGE_CODE_DANISH = 'da';
    const LANGUAGE_CODE_DUTCH = 'nl';
    const LANGUAGE_CODE_ENGLISH = 'en';
    const LANGUAGE_CODE_ESTONIAN = 'et';
    const LANGUAGE_CODE_FINNISH = 'fi';
    const LANGUAGE_CODE_FRENCH = 'fr';
    const LANGUAGE_CODE_GERMAN = 'de';
    const LANGUAGE_CODE_GREEK = 'el';
    const LANGUAGE_CODE_HAITIAN = 'ht';
    const LANGUAGE_CODE_HEBREW = 'he';
    const LANGUAGE_CODE_HINDI = 'hi';
    const LANGUAGE_CODE_HUNGARIAN = 'hu';
    const LANGUAGE_CODE_ICELANDIC = 'is';
    const LANGUAGE_CODE_INDONESIAN = 'id';
    const LANGUAGE_CODE_IRISH = 'ga';
    const LANGUAGE_CODE_ITALIAN = 'it';
    const LANGUAGE_CODE_JAPANESE = 'ja';
    const LANGUAGE_CODE_KAZAKH = 'kk';
    const LANGUAGE_CODE_KOREAN = 'ko';
    const LANGUAGE_CODE_LAO = 'lo';
    const LANGUAGE_CODE_LATIN = 'la';
    const LANGUAGE_CODE_LATVIAN = 'lv';
    const LANGUAGE_CODE_LITHUANIAN = 'lt';
    const LANGUAGE_CODE_MALAY = 'ms';
    const LANGUAGE_CODE_NORWEGIAN = 'no';
    const LANGUAGE_CODE_PERSIAN = 'fa';
    const LANGUAGE_CODE_POLISH = 'pl';
    const LANGUAGE_CODE_PORTUGUESE = 'pt';
    const LANGUAGE_CODE_PUNJABI = 'pa';
    const LANGUAGE_CODE_ROMANIAN = 'ro';
    const LANGUAGE_CODE_RUSSIAN = 'ru';
    const LANGUAGE_CODE_SANSKRIT = 'sa';
    const LANGUAGE_CODE_SLOVAK = 'sk';
    const LANGUAGE_CODE_SLOVENIAN = 'sl';
    const LANGUAGE_CODE_SPANISH = 'es';
    const LANGUAGE_CODE_SPANISH_LATIN_AMERICA = 'es-419';
    const LANGUAGE_CODE_SWEDISH = 'sv';
    const LANGUAGE_CODE_TAGALOG = 'tl';
    const LANGUAGE_CODE_TAMIL = 'ta';
    const LANGUAGE_CODE_TELUGU = 'te';
    const LANGUAGE_CODE_THAI = 'th';
    const LANGUAGE_CODE_TURKISH = 'tr';
    const LANGUAGE_CODE_UKRAINIAN = 'uk';
    const LANGUAGE_CODE_URDU = 'ur';
    const LANGUAGE_CODE_VIETNAMESE = 'vi';
    const LANGUAGE_CODE_ZULU = 'zu';

    public static $languages = [
        self::LANGUAGE_CODE_AFRIKAANS => 'Afrikaans',
        self::LANGUAGE_CODE_ARABIC => 'Arabic',
        self::LANGUAGE_CODE_BENGALI => 'Bengali',
        self::LANGUAGE_CODE_BULGARIAN => 'Bulgarian',
        self::LANGUAGE_CODE_CANTONESE => 'Cantonese',
        self::LANGUAGE_CODE_CATALAN => 'Catalan',
        self::LANGUAGE_CODE_CHINESE_SIMPLIFIED => 'Chinese (Simplified)',
        self::LANGUAGE_CODE_CHINESE_TRADITIONAL => 'Chinese (Traditional)',
        self::LANGUAGE_CODE_CROATIAN => 'Croatian',
        self::LANGUAGE_CODE_CZECH => 'Czech',
        self::LANGUAGE_CODE_DANISH => 'Danish',
        self::LANGUAGE_CODE_DUTCH => 'Dutch',
        self::LANGUAGE_CODE_ENGLISH => 'English',
        self::LANGUAGE_CODE_ESTONIAN => 'Estonian',
        self::LANGUAGE_CODE_FINNISH => 'Finnish',
        self::LANGUAGE_CODE_FRENCH => 'French',
        self::LANGUAGE_CODE_GERMAN => 'German',
        self::LANGUAGE_CODE_GREEK => 'Greek',
        self::LANGUAGE_CODE_HAITIAN => 'Haitian',
        self::LANGUAGE_CODE_HEBREW => 'Hebrew',
        self::LANGUAGE_CODE_HINDI => 'Hindi',
        self::LANGUAGE_CODE_HUNGARIAN => 'Hungarian',
        self::LANGUAGE_CODE_ICELANDIC => 'Icelandic',
        self::LANGUAGE_CODE_INDONESIAN => 'Indonesian',
        self::LANGUAGE_CODE_IRISH => 'Irish',
        self::LANGUAGE_CODE_ITALIAN => 'Italian',
        self::LANGUAGE_CODE_JAPANESE => 'Japanese',
        self::LANGUAGE_CODE_KAZAKH => 'Kazakh',
        self::LANGUAGE_CODE_KOREAN => 'Korean',
        self::LANGUAGE_CODE_LAO => 'Lao',
        self::LANGUAGE_CODE_LATIN => 'Latin',
        self::LANGUAGE_CODE_LATVIAN => 'Latvian',
        self::LANGUAGE_CODE_LITHUANIAN => 'Lithuanian',
        self::LANGUAGE_CODE_MALAY => 'Malay',
        self::LANGUAGE_CODE_NORWEGIAN => 'Norwegian',
        self::LANGUAGE_CODE_PERSIAN => 'Persian',
        self::LANGUAGE_CODE_POLISH => 'Polish',
        self::LANGUAGE_CODE_PORTUGUESE => 'Portuguese',
        self::LANGUAGE_CODE_PUNJABI => 'Punjabi',
        self::LANGUAGE_CODE_ROMANIAN => 'Romanian',
        self::LANGUAGE_CODE_RUSSIAN => 'Russian',
        self::LANGUAGE_CODE_SANSKRIT => 'Sanskrit',
        self::LANGUAGE_CODE_SLOVAK => 'Slovak',
        self::LANGUAGE_CODE_SLOVENIAN => 'Slovenian',
        self::LANGUAGE_CODE_SPANISH => 'Spanish',
        self::LANGUAGE_CODE_SPANISH_LATIN_AMERICA => 'Spanish (Latin America)',
        self::LANGUAGE_CODE_SWEDISH => 'Swedish',
        self::LANGUAGE_CODE_TAGALOG => 'Tagalog',
        self::LANGUAGE_CODE_TAMIL => 'Tamil',
        self::LANGUAGE_CODE_TELUGU => 'Telugu',
        self::LANGUAGE_CODE_THAI => 'Thai',
        self::LANGUAGE_CODE_TURKISH => 'Turkish',
        self::LANGUAGE_CODE_UKRAINIAN => 'Ukrainian',
        self::LANGUAGE_CODE_URDU => 'Urdu',
        self::LANGUAGE_CODE_VIETNAMESE => 'Vietnamese',
        self::LANGUAGE_CODE_ZULU => 'Zulu',
    ];
}